image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - apt update ; apt upgrade -y;
  - apt install -y cmake doxygen graphviz python3 python3-pip ninja-build libnuma-dev
  - python --version ; pip --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install conan gcovr meson pyelftools
  - conan profile detect --force

stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - chmod +x ./build.sh
    - ./build.sh -s

build:Debug:
  stage: build
  script:
    - ./build.sh -c Debug -b

build:Release:
  stage: build
  script:
    - ./build.sh -c Release -b

deploy:
  stage: deploy
  script: echo "deploy success"
  environment: production

