name: build lazybsd

on:
  push:
    branches:
      - master
      - develop
      - feature/*

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: false
        submodules: 'recursive'

    - name: 安装软件
      run: |
        sudo apt -y update
        sudo apt install -y doxygen graphviz python3 python3-pip ninja-build libnuma-dev ccache

    - name: Cache Conan2
      id: Cache_Conan2
      uses: actions/cache@v4
      with:
        path: ~/.conan2
        key: ${{ matrix.build_type }}-conan2

    - name: Cache DPDK
      id: Cache_DPDK
      uses: actions/cache@v4
      with:
        path: ./dpdk/build
        key: cache-dpdk-build

    - name: python package install
      run: |
        pip install gcovr
        pip3 install conan
        pip3 install meson
        pip3 install pyelftools
        conan profile detect --force

    - name: Setup ccache
      uses: Chocobo1/setup-ccache-action@v1
      with:
        install_ccache: false
        update_packager_index: false

    - name: chmod +x build.sh
      run: |
        chmod +x build.sh

    - name: 编译DPDK
      run: |
        ./build.sh -s

    - name: 编译lazybsd
      run: |
        ./build.sh -c ${{ matrix.build_type }} -l -b

    - uses: codecov/codecov-action@v4
      if: matrix.build_type == 'Debug'
      with:
        fail_ci_if_error: true # optional (default = false)
        files: ${{github.workspace}}/build/test/TestXml.xml
        flags: unittests # optional
        name: codecov-umbrella # optional
        token: ${{ secrets.CODECOV_TOKEN }} # required
        verbose: true # optional (default = false)


