name: build lazybsd

on:
  push:
    branches:
      - master
      - develop
      - feature/*

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: false
    
    - name: 安装软件
      run: |
        sudo apt -y update
        sudo apt -y upgrade
        sudo apt -y  doxygen graphviz python3 python3-pip ninja-build

    - name: conan install
      run: |
        pip3 install conan
        conan profile detect --force

    - name: 编译lazybsd
      run: |
        chmod +x ./build.sh
        ./build.sh -c ${{ matrix.build_type }}

